# Generated by Django 3.1.4 on 2021-01-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='prefix',
            field=models.CharField(default='A', max_length=1000),
            preserve_default=False,
        ),
    ]
